version: '3'
services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    container_name: hello_backend
    depends_on:
      - web
      - api
  web:
    image: hello-web:1.0
    ports:
      - 3000:3000
    container_name: hello-web
  api:
    image: hello-api:1.0
    ports:
      - 8080:8080
    container_name: hello-api