version: '3'
services:
#  nginx:
#    image: nginx:1.18.0
#    ports:
#      - 80:80
#    volumes:
#      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
#    container_name: hello_backend
#    depends_on:
#      - web
#      - api
  web:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    ports:
      - 3000:8080
    container_name: hello-web
  api:
    build:
      context: ./complete
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: hello-api